del sclient\Launcher.class
del sclient\gui\LogInFrame.class
del sclient\gui\LogInFrame$1.class
del sclient\gui\LogInFrame$ConnectButtonListener.class
del sclient\gui\QuizFrame.class
del sclient\gui\QuizFrame$1.class
del sclient\gui\QuizFrame$QuizButtonListener.class
del sclient\network\Connection.class
del sclient\network\ConnectionListener.class
del server\IListener.class
del server\InstructorProcessor.class
del server\Server.class
del server\Session.class
del server\SListener.class
del server\StudentProcessor.class
del iclient\Launcher.class
del iclient\network\Connection.class
del iclient\network\ConnectionListener.class
del iclient\gui\CreateFrame.class
del iclient\gui\SessionFrame.class
del iclient\gui\CreateFrame$ConnectButtonListener.class
del iclient\gui\SessionFrame$AcceptAnswerButtonListener.class
del iclient\gui\SessionFrame$EndSessionButtonListener.class
del iclient\gui\SessionFrame$NewQuestionButtonListener.class
del iclient\gui\SessionFrame$RejectAnswerButtonListener.class
del iclient\gui\CreateFrame$1.class
del iclient\gui\SessionFrame$1.class
del iclient\data\Student.class
cls
