CREATE TABLE ROLES
(
	ROLE_ID		INT		NOT NULL,
	NAME		VARCHAR(255)	NOT NULL,
	PRIMARY KEY (ROLE_ID)
);

CREATE TABLE USERS
(
	USER_ID		INT		NOT NULL	AUTO_INCREMENT,
	PASSWORD	VARCHAR(255)	NOT NULL,
	ROLE_ID		INT		NOT NULL,
	PRIMARY KEY (USER_ID),
	FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID)
);